spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contabilidad
    username: kevin
    password: kevin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE               
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  
    org.springframework.transaction: DEBUG

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  address: 0.0.0.0
  port: 5999
  servlet:
    context-path: /contabilidad-ms 

kafka:
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    group-id: mi-grupo-contable
topic:
  nameCuenta: cuentacontable
  nameInventario: cuentacontable
  nameSriGetFactura: getfacturasri
  inventarioAsientoContable: inventario-asiento-contable
jwt:
  secret: your-new-32-characters-or-more-secret-key
