spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contabilidad
    username: kevin
    password: kevin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
    org.springdoc: DEBUG  # ← Agrega esto para debug de Swagger

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

server:
  address: 0.0.0.0
  port: 6000

jwt:
  secret: your-new-32-characters-or-more-secret-key
